'use client';

import React from 'react'
import { log } from '@/lib/axiom/client-log'
import { 
  IconPlus, 
  IconMinus, 
  IconEdit, 
  IconTrash, 
  IconUser, 
  IconUsers, 
  IconSettings, 
  IconSearch, 
  IconX, 
  IconCheck, 
  IconChevronDown, 
  IconChevronUp, 
  IconChevronLeft, 
  IconChevronRight, 
  IconLoader2, 
  IconMail, 
  IconPhone, 
  IconBuilding, 
  IconEye, 
  IconEyeOff,
  IconHome,
  IconDashboard,
  IconMenu2,
  IconBell,
  IconLogout,
  IconBriefcase,
  IconFileText,
  IconCalendar,
  IconShieldCheck,
  IconCreditCard,
  IconPlug,
  IconChartBar,
  IconUsersGroup,
  IconChevronsDown,
  IconSparkles,
  IconCertificate,
  IconSelector,
  IconArrowUp,
  IconSend,
  IconMessage,
  IconHelp,
  IconUserCheck,
  IconMessages,
  IconGitBranch,
  IconAlertCircle,
  IconRobot,
  IconMessageCircle,
  IconTool,
  IconDatabase,
  IconBrain,
  IconBolt,
  IconCopy,
  IconMapPin,
  IconCurrencyDollar,
  IconClock,
  IconCode,
  IconCirclePlus,
  IconAdjustmentsHorizontal,
  IconArrowsSort,
  IconArrowDown,
  IconDots,
  IconChevronsLeft,
  IconChevronsRight,
  IconArchive,
  IconPlayerPlay,
  IconPlayerPause,
  IconSquare,
  IconSchool,
  IconCircle,
  IconGripVertical,
  IconBorderHorizontal,
  IconPlanet,
  IconUpload,
  IconDownload,
  IconBrandLinkedin,
  IconUserPlus,
  IconBriefcaseOff,
  IconAlertTriangle,
  IconRefresh,
  IconExternalLink,
  IconBrandGithub,
  IconBrandGoogle,
  IconGlobe,
  IconTimeline,
  IconDotsVertical,  
  IconBriefcase2,
  IconLock,
  IconBraces,
  IconDeviceFloppy,
  IconArchiveOff,
  IconCircleCheck,
  IconTrendingUp,
  IconDice6,
  IconCircleX,
  IconTarget,
  IconGauge,
  IconHash,
  IconInfoCircle,
  IconCloudUpload,
  IconFilePlus,
  IconLifebuoy,
  IconCoins,
} from '@tabler/icons-react'

// Icon name to component mapping
const iconMap = {
  plus: IconPlus,
  minus: IconMinus,
  edit: IconEdit,
  trash: IconTrash,
  user: IconUser,
  users: IconUsers,
  settings: IconSettings,
  search: IconSearch,
  x: IconX,
  check: IconCheck,
  'chevron-down': IconChevronDown,
  'chevron-up': IconChevronUp,
  'chevron-left': IconChevronLeft,
  'chevron-right': IconChevronRight,
  'chevrons-up-down': IconChevronsDown,
  selector: IconSelector,
  loader: IconLoader2,
  mail: IconMail,
  phone: IconPhone,
  building: IconBuilding,
  eye: IconEye,
  'eye-off': IconEyeOff,
  home: IconHome,
  dashboard: IconDashboard,
  menu: IconMenu2,
  bell: IconBell,
  logout: IconLogout,
  briefcase: IconBriefcase,
  'file-text': IconFileText,
  calendar: IconCalendar,
  'shield-check': IconShieldCheck,
  'badge-check': IconCertificate,
  'credit-card': IconCreditCard,
  plug: IconPlug,
  'chart-bar': IconChartBar,
  'user-group': IconUsersGroup,
  sparkles: IconSparkles,
  'arrow-up': IconArrowUp,
  send: IconSend,
  'message-square': IconMessage,
  'help-circle': IconHelp,
  'user-check': IconUserCheck,
  messages: IconMessages,
  workflow: IconGitBranch,
  'loader-2': IconLoader2,
  'alert-circle': IconAlertCircle,
  bot: IconRobot,
  'message-circle': IconMessageCircle,
  tool: IconTool,
  database: IconDatabase,
  brain: IconBrain,
  zap: IconBolt,
  bolt: IconBolt,
  copy: IconCopy,
  'map-pin': IconMapPin,
  'dollar-sign': IconCurrencyDollar,
  clock: IconClock,
  code: IconCode,
  'plus-circle': IconCirclePlus,
  'adjustments-horizontal': IconAdjustmentsHorizontal,
  'arrows-sort': IconArrowsSort,
  'arrow-down': IconArrowDown,
  'arrow-left': IconChevronLeft,
  'dots-horizontal': IconDots,
  'chevrons-left': IconChevronsLeft,
  'chevrons-right': IconChevronsRight,
  archive: IconArchive,
  play: IconPlayerPlay,
  pause: IconPlayerPause,
  square: IconSquare,
  'graduation-cap': IconSchool,
  circle: IconCircle,
  'grip-vertical': IconGripVertical,
  'border-horizontal': IconBorderHorizontal,
  planet: IconPlanet,
  upload: IconUpload,
  download: IconDownload,
  'brand-linkedin': IconBrandLinkedin,
  'brand-github': IconBrandGithub,
  'brand-google': IconBrandGoogle,
  'user-plus': IconUserPlus,
  'briefcase-plus': IconBriefcaseOff,
  construction: IconTool,
  'alert-triangle': IconAlertTriangle,
  'refresh-cw': IconRefresh, 
  'external-link': IconExternalLink,
  'globe': IconGlobe,
  timeline: IconTimeline,
  dot: IconDotsVertical,
  'dots-vertical': IconDotsVertical,
  'briefcase-2': IconBriefcase2,
  'briefcase-off': IconBriefcaseOff,
  lock: IconLock,
  'braces': IconBraces,
  'git-branch': IconGitBranch,
  'device-floppy': IconDeviceFloppy,
  'player-play': IconPlayerPlay,
  'player-pause': IconPlayerPause,
  'archive-restore': IconArchiveOff,
  'check-circle': IconCircleCheck,
  'trending-up': IconTrendingUp,
  'more-horizontal': IconDots,
  'dice-6': IconDice6,
  'x-circle': IconCircleX,
  save: IconDeviceFloppy,
  target: IconTarget,
  gauge: IconGauge,
  hash: IconHash,
  'info': IconInfoCircle,
  'cloud-upload': IconCloudUpload,
  'file-plus': IconFilePlus,
  'lifebuoy': IconLifebuoy,
  'coins': IconCoins,
} as const

export type IconName = keyof typeof iconMap

// Infer props type from Tabler icon components
type TablerIconProps = React.ComponentProps<typeof IconPlus>

interface IconProps extends Omit<TablerIconProps, 'name'> {
  name: IconName
}

const LOG_SOURCE = 'components/icon';

/**
 * Icon component abstraction using Tabler icons
 * Usage: <Icon name="plus" size={16} />
 */
export function Icon({ name, size = 20, ...props }: IconProps) {
  const IconComponent = iconMap[name]

  if (!IconComponent) {
    if (process.env.NODE_ENV !== 'production') {
      log.warn(LOG_SOURCE, 'Icon not found in iconMap', { iconName: name })
    }
    return null
  }

  return <IconComponent size={size} {...props} />
}

// Re-export common icon props type for convenience
export type { TablerIconProps as TablerIconProps } 
